### PR TITLE
typo: lable -> label

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by IoTGirl** [comment]
This error still exists in the live page and the images seem to be missing at https://docs.microsoft.com/en-us/bingmaps/articles/create-a-custom-map-url

**Comment by nschonni** [comment]
@DRMap this are still issues on the live docs, are you planning to fix this elsewhere or are these docs just abandoned now?

**Comment by DRMap** [comment]
Cleaning up the documentation repository. The ‘lable’ typo should be fixed now. Would you mind double checking?

**Comment by nschonni** [comment]
Looks like it's OK on the live site now.
FYI, closing a bunch of PRs without a comment  after they've sat open for 2 years isn't a good way to run on OSS project. Closing the is fine, but you should mention that you've already fixed them on an internal branch. I'm not sure if the rest of the PRs you closed are actually addressed, but i'm not spending any more energy here

**Pull request closed without merging**
